---
title: "**North Korea Human Rights Violations Map**"
author: Jieun Byeon
documentclass: article
format: 
  pdf:
    citation_package: natbib
    keep_tex: true
    link-citations: true
    fig_caption: true
    latex_engine: xelatex
    code-block-bg: light
    code-block-border-left: "#31BAE9"
    linkcolor: black
    urlcolor: black
    highlight-style: atom-one
header-includes:
  -  \usepackage{hyperref}
  -  \usepackage{mathpazo}
  -  \usepackage{bookmark}
  -  \definecolor{light}{HTML}{EEEEEE}
  -  \definecolor{highlight}{HTML}{9A2A2A}
  -  \definecolor{dark}{HTML}{330033}
  -  \usepackage{setspace}\singlespacing
  -  \usepackage{fvextra}
  -  \setmainfont[ItalicFont = {TeXGyrePagella-Italic}]{TeX Gyre Pagella}
  -  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
  -  \setmonofont{Fira Code}[Contextuals=Alternate]
  -  \makeatletter
  -  \renewcommand*\verbatim@nolig@list{}
  -  \makeatother
biblio-style: apsr
geometry: margin=1in
fontsize: 12pt
link-citation: true
indent: true
---

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = "/Users/howardliu/Library/CloudStorage/OneDrive-UniversityofSouthCarolina/NK_project/") # change to my wd
# opts_knit$set(root.dir = "/Users/jieun/Documents/lab/NK")
```

```{r, echo=FALSE, include=FALSE}
rm(list = ls())      
library(tidyverse)
library(sf)
library(tools)
library(RColorBrewer)
library(viridis)
library(patchwork)
library(scales)
mycolors <- colorRampPalette(brewer.pal(name="Dark2", n = 8))(14)
```



```{r}
NKKorean <-  read.csv("/Users/jieun/Downloads/North Korean Prison Database -2024-01-19T02_56_23.323Z.csv") # where is this?
NK_location <- readxl::read_xlsx("Data/locations.xlsx") |> dplyr::select(-3)
nk_prisoner <- read.csv("Data/NKprison.csv")
north_korea <- st_read("Data/PRK_adm2.shp")
```

```{r}
nk_prisoner <- nk_prisoner %>% 
  filter(!is.na(Year.of.Violation)) %>% 
  separate_rows(Year.of.Violation, sep = "\\|") %>%
  filter(Year.of.Violation != "") %>%
  filter(!is.na(Location.Where.the.Violation.Occurred)) %>% 
  separate_rows(Location.Where.the.Violation.Occurred, sep = "\\|") %>%
  filter(Location.Where.the.Violation.Occurred != "") %>%
  filter(!is.na(Province.Where.the.Violation.Occurred)) %>% 
  separate_rows(Province.Where.the.Violation.Occurred, sep = "\\|") %>%
  filter(Province.Where.the.Violation.Occurred != "")
nk_prisoner$Year.of.Violation <- as.numeric(as.character(nk_prisoner$Year.of.Violation))

nk_prisoner <- nk_prisoner %>%
  mutate(Location.Where.the.Violation.Occurred = trimws(Location.Where.the.Violation.Occurred))
```

```{r}
NK <- nk_prisoner %>% 
  filter(Violation.Type %in% c("Rape & Other Forms of Sexual Violence", "Torture & CID","Forced Labour")) %>%
  select(Year.of.Violation, Violation.Type, Location.Where.the.Violation.Occurred, Province.Where.the.Violation.Occurred)

location_category <- function(location) {
  if (grepl("Detention Centre", location)) {
    return("Detention Centre")
  } else if (grepl("Holding Centre", location)) {
    return("Holding Centre")
  } else if (grepl("Labour Training Centre", location)) {
    return("Labour Training Centre")
  } else if (grepl("Re-education Camp", location)) {
    return("Re-education Camp")
  } else {
    return("Others")
  }
}

NK <- NK %>%
  mutate(Location_Category = sapply(Location.Where.the.Violation.Occurred, location_category))


NK1 <- NK %>% 
  filter(Violation.Type %in% c("Rape & Other Forms of Sexual Violence")) %>%
  select(Year.of.Violation, Violation.Type, Location.Where.the.Violation.Occurred, Province.Where.the.Violation.Occurred, Location_Category)

ggplot(data = NK1, aes(x = Province.Where.the.Violation.Occurred)) +
  geom_bar(fill = "lightgreen") +
  labs(title = "Rape", x = "Region", y = "Frequency") +
  scale_x_discrete(labels = label_wrap(10)) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(hjust = 0.5, size = 8))

NK2 <- NK %>% 
  filter(Violation.Type %in% c("Torture & CID")) %>%
  select(Year.of.Violation, Violation.Type, Location.Where.the.Violation.Occurred, Province.Where.the.Violation.Occurred, Location_Category)

ggplot(data = NK2, aes(x = Province.Where.the.Violation.Occurred)) +
  geom_bar(fill = "lightgreen") +
  labs(title = "Torture", x = "Region", y = "Frequency") +
  scale_x_discrete(labels = label_wrap(10)) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(hjust = 0.5, size = 8))
NK3 <- NK %>% 
  filter(Violation.Type %in% c("Forced Labour")) %>%
  select(Year.of.Violation, Violation.Type, Location.Where.the.Violation.Occurred, Province.Where.the.Violation.Occurred, Location_Category)

ggplot(data = NK3, aes(x = Province.Where.the.Violation.Occurred)) +
  geom_bar(fill = "lightgreen") +
  labs(title = "Forced Labour", x = "Region", y = "Frequency") +
  scale_x_discrete(labels = label_wrap(10)) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(hjust = 0.5, size = 8))
```

```{r}
NK1.1 <- NK1 %>%
  group_by(Location_Category) %>%
  summarise(Frequency = n())

n1<- ggplot(data = NK1.1, aes(x = Frequency, y = fct_rev(Location_Category))) +
  geom_col() +
  labs(title = "Rape", x = "Frequency", y = "Region") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 20),
        axis.text.y = element_text(hjust = 0.5, size = 20))

# Most of rapes and sexual violances happened in Detention Center and Holding center
# The detention center for repatriation of North Korean defectors is primarily located in Onsong, Musan, Hoeryong, Sinuiju, and Hyesan.

NK2.1 <- NK2 %>%
  group_by(Location_Category) %>%
  summarise(Frequency = n())

# Torture happened in Detention Center, Holding Center, Labor Training Center, and Re-education camp (Almost all kinds of the locations)
n2<- ggplot(data = NK2.1, aes(x = Frequency, y = fct_rev(Location_Category))) +
  geom_col() +
  labs(title = "Torture", x = "Frequency", y = "Region") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5,size = 20),
        axis.text.y = element_text(hjust = 0.5, size = 20))

NK3.1 <- NK3 %>%
  group_by(Location_Category) %>%
  summarise(Frequency = n())

# Forced Labor happened in Holding Center, Labor Training Center, and Re-education camp
# Biggest Re-education camps: Hoeryong (North Hamgyong) Gaechon (South Pyongan)
# Labor Training Centers: Gaechon (South Pyongan), Chungsan (South Pyongan), Hoeryong (North Hamgyong), Hyesan (Ryanggang), Musan (North Hamgyong), Onsong (North Hamgyong)

# South Pyongan Province: Gaechon, Chungsan
# Gaechon: The largest anthracite production area in North Korea.
# Chungsan: Rich in resources such as iron, titanium, nickel, spodumene, ferroalloy, and molybdenum.

n3 <- ggplot(data = NK3.1, aes(x = Frequency, y = fct_rev(Location_Category))) +
  geom_col() +
  labs(title = "Forced Labor", x = "Frequency", y = "Region") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5,size = 20),
        axis.text.y = element_text(hjust = 0.5, size = 20))

n1 + n2 + n3 + patchwork::plot_layout(nrow = 3)
ggsave("1.png", width = 30, height = 20, units = "in")
```

```{r, echo=FALSE}
nk_prisoner <- nk_prisoner %>%
  mutate(period = 
           case_when(Year.of.Violation>= 1990 & Year.of.Violation < 1996 ~ "P1",
                     Year.of.Violation > 1995 & Year.of.Violation < 2001 ~ "P2",
                     Year.of.Violation > 2000 & Year.of.Violation < 2006 ~ "P3",
                     Year.of.Violation > 2005 & Year.of.Violation < 2011 ~ "P4",
                     Year.of.Violation > 2010 & Year.of.Violation < 2016 ~ "P5",
                     Year.of.Violation > 2015 & Year.of.Violation < 2021 ~ "P6",
                     is.na(Year.of.Violation) ~ NA_character_)) %>%
  mutate(period2 = case_when(Year.of.Violation>= 1990 & Year.of.Violation < 2000 ~ "P1",
                     Year.of.Violation > 2001 & Year.of.Violation < 2010 ~ "P2",
                     Year.of.Violation > 2011 & Year.of.Violation < 2020 ~ "P3",
                     is.na(Year.of.Violation) ~ NA_character_))

nk_prisoner <- nk_prisoner %>%
  mutate(violation.category = case_when(
    Violation.Type %in% c("Forced Labour", 
                          "Rape & Other Forms of Sexual Violence", 
                          "Torture & CID", "Arbitrary Deprivation of Liberty", 
                          "Denial of the Right to Life", 
                          "Sexual and Gender-based Violence ") ~ "Physical Integrity Rights",
    Violation.Type %in% c("Violation of Freedom of Expression", 
                          "Denial of the Right to Freedom of Conscience, Thought and Religion", 
                          "Violation of Right to Health", "Denial of the Right to a Fair Trial ", 
                          "Denial of the Rights of Detainees with Disabilities", "Violation of Rights of Children")  ~ "Empowerment Rights",  TRUE ~ "Other"))
```

```{r, echo=FALSE}
nk_prisoner <- nk_prisoner %>%
  left_join(NK_location, by = c("Location.Where.the.Violation.Occurred"))

nk_prisoner <- nk_prisoner %>%
  separate(Locations, into = c("longitude", "latitude"), sep = ", ", remove = FALSE)

nk_prisoner$longitude <- as.numeric(nk_prisoner$longitude)
nk_prisoner$latitude <- as.numeric(nk_prisoner$latitude)
```

```{r, echo=FALSE}
#### Relabel the province name
north_korea |> mutate(
  NAME_kr = case_when(
    NAME_1 %in% "Chagang-do" ~ "Chagang",
    NAME_1 %in% "Hamgyŏng-bukto" ~ "North Hamgyong",
    NAME_1 %in% "Hamgyŏng-namdo" ~ "South Hamgyong",
    NAME_1 %in% "Hwanghae-bukto" ~ "North Hwanghae",
    NAME_1 %in% "Hwanghae-namdo" ~ "South Hwanghae",
    NAME_1 %in% "Kaesŏng" ~ "Kaesong",
    NAME_1 %in% "Kangwŏn-do" ~ "Kangwon",
    NAME_1 %in% "Kumgangsan" ~ "Kangwon",
    NAME_1 %in% "P'yŏngan-bukto" ~ "North Pyongan",
    NAME_1 %in% "P'yŏngan-namdo" ~ "South Pyongan",
    NAME_1 %in% "P'yŏngyang" ~ "Pyongyang",
    NAME_1 %in% "Rasŏn" ~ "Rason",
    NAME_1 %in% "Ryanggang" ~ "Ryanggang",
    NAME_1 %in% "Sinŭiju" ~ "North Pyongan",
    T ~ NA_character_
  )
) -> north_korea

nk_map_location <- 
  north_korea |> full_join(
  nk_prisoner, by = c("NAME_kr" = "Province.Where.the.Violation.Occurred")
)
```

```{r, echo=FALSE}
prison_period <- nk_map_location |> dplyr::select(period, violation.category, Violation.Type, latitude, longitude) |> 
  as_tibble()
prison_period$geometry <- NULL

sum_prison_period <- 
  prison_period |> drop_na() |> group_by(period, violation.category, Violation.Type, latitude, longitude) |> count()

sum_prison_period <- st_as_sf(sum_prison_period, coords = c("latitude", "longitude"), 
         agr = "constant",
         crs = 4326)
```

```{r, echo=FALSE}
int <- sf::st_intersects(north_korea, sum_prison_period)

joined_north_korea <- north_korea |> st_join(sum_prison_period) 

sum_joined_north_korea <- joined_north_korea |> 
  drop_na(period, VARNAME_2, Violation.Type, violation.category) |> 
  group_by(period, VARNAME_2, Violation.Type, violation.category) |>
  summarize(n = sum(n)) 

my_breaks <- c(seq(0, 50, 10))
quantile(sum_joined_north_korea$n, probs = c(seq(0, 1, 0.2)), na.rm = T)
sum_joined_north_korea |> 
  mutate(n_agg = case_when(
    n <  10 ~ 1L,
    n >= 10 & n < 50 ~ 2L,
    n >= 50 & n < 100 ~ 3L,
    n >= 100 & n < 200 ~ 4L,
    n >= 200 & n < 300 ~ 5L,
    n >= 300 & n < 400 ~ 6L,
    n >= 400 & n < 500 ~ 7L,
    n >= 500 ~ 8L,
    T ~ NA_integer_
  )) ->
  sum_joined_north_korea
```

```{r, echo=FALSE}
i1<- north_korea |> 
  ggplot() +
  geom_sf(fill = "white") + 
  geom_sf(
    data = sum_joined_north_korea |> 
      dplyr::filter(Violation.Type %in% "Forced Labour"),
    aes(geometry = geometry, fill = n_agg),
    alpha = 0.9, show.legend = TRUE, stat = "sf_coordinates") +
  scale_fill_viridis(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8),
    limits = c(1, 8),
    labels = c("Under 10", "10-50", "50-100", "100-200", 
               "200-300", "300-400", "400-500", "Over 500"),
    direction = -1) +
  ggrepel::geom_label_repel(
    data = sum_joined_north_korea |> 
      dplyr::filter(Violation.Type %in% "Forced Labour"),
    aes(geometry = geometry, label = n),
    max.overlaps=Inf,
    show.legend = F,
    stat = "sf_coordinates"
  ) + labs(subtitle = "Violation Type: Forced Labour ") +
  theme_void() + theme(legend.title = element_blank())

i2<- north_korea |> 
  ggplot() +
  geom_sf(fill = "white") + 
  geom_sf(
    data = sum_joined_north_korea |> 
      dplyr::filter(Violation.Type %in% "Torture & CID"),
    aes(geometry = geometry, fill = n_agg),
    alpha = 0.9, show.legend = TRUE, stat = "sf_coordinates") +
  scale_fill_viridis(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8),
    limits = c(1, 8),
    labels = c("Under 10", "10-50", "50-100", "100-200", 
               "200-300", "300-400", "400-500", "Over 500"),
    direction = -1) +
  ggrepel::geom_label_repel(
    data = sum_joined_north_korea |> 
      dplyr::filter(Violation.Type %in% "Torture & CID"),
    aes(geometry = geometry, label = n),
    max.overlaps=Inf,
    show.legend = F,
    stat = "sf_coordinates"
  ) + labs(subtitle = "Violation Type: Torture & CID ") +
  theme_void() + theme(legend.title = element_blank())

i3<- north_korea |> 
  ggplot() +
  geom_sf(fill = "white") + 
  geom_sf(
    data = sum_joined_north_korea |> 
      dplyr::filter(Violation.Type %in% "Rape & Other Forms of Sexual Violence"),
    aes(geometry = geometry, fill = n_agg),
    alpha = 0.9, show.legend = TRUE, stat = "sf_coordinates") +
  scale_fill_viridis(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8),
    limits = c(1, 8),
    labels = c("Under 10", "10-50", "50-100", "100-200", 
               "200-300", "300-400", "400-500", "Over 500"),
    direction = -1) +
  ggrepel::geom_label_repel(
    data = sum_joined_north_korea |> 
      dplyr::filter(Violation.Type %in% "Rape & Other Forms of Sexual Violence"),
    aes(geometry = geometry, label = n),
    max.overlaps=Inf,
    show.legend = F,
    stat = "sf_coordinates"
  ) + labs(subtitle = "Violation Type: Rape & Other Forms of Sexual Violence") +
  theme_void() + theme(legend.title = element_blank())

# i4 <- north_korea |> 
#   ggplot() +
#   geom_sf(fill = "white") + 
#   geom_sf(
#     data = sum_joined_north_korea |> 
#       dplyr::filter(Violation.Type %in% "Denial of the Right to Life"),
#     aes(geometry = geometry, fill = n_agg),
#     alpha = 0.9, show.legend = TRUE, stat = "sf_coordinates") +
#   scale_fill_viridis(
#     breaks = c(1, 2, 3, 4, 5, 6, 7, 8),
#     limits = c(1, 8),
#     labels = c("Under 10", "10-50", "50-100", "100-200", 
#                "200-300", "300-400", "400-500", "Over 500"),
#     direction = -1) +
#   ggrepel::geom_label_repel(
#     data = sum_joined_north_korea |> 
#       dplyr::filter(Violation.Type %in% "Denial of the Right to Life"),
#     aes(geometry = geometry, label = n),
#     max.overlaps=Inf,
#     show.legend = F,
#     stat = "sf_coordinates"
#   ) + labs(subtitle = "Violation Type: Denial of the Right to Life") +
#   theme_void() + theme(legend.title = element_blank())

i1 + i2 + i3 + patchwork::plot_layout(ncol = 3)
ggsave("i.png", width = 30, height = 10, units = "in")
```

```{r plot-wider-bigger, echo=FALSE, message = FALSE}
# Colored map
p1v1 <- 
  north_korea |> 
  ggplot() +
  geom_sf(fill = "white") + 
  geom_sf(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P1" & 
                      violation.category %in% "Physical Integrity Rights"),
    aes(geometry = geometry, fill = n_agg),
    alpha = 0.9, show.legend = TRUE, stat = "sf_coordinates") +
  scale_fill_viridis(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8),
    limits = c(1, 8),
    labels = c("Under 10", "10-50", "50-100", "100-200", 
               "200-300", "300-400", "400-500", "Over 500"),
    direction = -1) +
  ggrepel::geom_label_repel(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P1" &
                      violation.category %in% "Physical Integrity Rights"),
    aes(geometry = geometry, label = n),
    max.overlaps=Inf,
    show.legend = F,
    stat = "sf_coordinates"
  ) + labs(subtitle = "Period 1: 1990 ~ 1995\nViolation Type: Physical Integrity Rights") +
  theme_void() + theme(legend.title = element_blank())
p1v2 <-
  north_korea |> 
  ggplot() +
  geom_sf(fill = "white") + 
  geom_sf(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P1" & 
                      violation.category %in% "Empowerment Rights"),
    aes(geometry = geometry, fill = n_agg),
    alpha = 0.9, show.legend = TRUE, stat = "sf_coordinates") +
  scale_fill_viridis(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8),
    limits = c(1, 8),
    labels = c("Under 10", "10-50", "50-100", "100-200", 
               "200-300", "300-400", "400-500", "Over 500"),
    direction = -1) +
  ggrepel::geom_label_repel(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P1" &
                      violation.category %in% "Empowerment Rights"),
    aes(geometry = geometry, label = n),
    max.overlaps=Inf,
    show.legend = F,
    stat = "sf_coordinates"
  ) + labs(subtitle = "Period 1: 1990 ~ 1995\nViolation Type: Empowerment Rights") +
  theme_void() + theme(legend.title = element_blank())

p1v1 + p1v2 + patchwork::plot_layout(ncol = 2)
#ggsave("p1m.png", width = 20, height = 10, units = "in")

p2v1 <- 
  north_korea |> 
  ggplot() +
  geom_sf(fill = "white") + 
  geom_sf(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P2" & 
                      violation.category %in% "Physical Integrity Rights"),
    aes(geometry = geometry, fill = n_agg),
    alpha = 0.9, show.legend = TRUE, stat = "sf_coordinates") +
  scale_fill_viridis(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8),
    limits = c(1, 8),
    labels = c("Under 10", "10-50", "50-100", "100-200", 
               "200-300", "300-400", "400-500", "Over 500"),
    direction = -1) +
  ggrepel::geom_label_repel(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P2" &
                      violation.category %in% "Physical Integrity Rights"),
    aes(geometry = geometry, label = n),
    max.overlaps=Inf,
    show.legend = F,
    stat = "sf_coordinates"
  ) + labs(subtitle = "Period 2: 1996 ~ 2000\nViolation Type: Physical Integrity Rights") +
  theme_void() + theme(legend.title = element_blank())

p2v2 <-
  north_korea |> 
  ggplot() +
  geom_sf(fill = "white") + 
  geom_sf(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P2" & 
                      violation.category %in% "Empowerment Rights"),
    aes(geometry = geometry, fill = n_agg),
    alpha = 0.9, show.legend = TRUE, stat = "sf_coordinates") +
  scale_fill_viridis(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8),
    limits = c(1, 8),
    labels = c("Under 10", "10-50", "50-100", "100-200", 
               "200-300", "300-400", "400-500", "Over 500"),
    direction = -1) +
  ggrepel::geom_label_repel(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P2" &
                      violation.category %in% "Empowerment Rights"),
    aes(geometry = geometry, label = n),
    max.overlaps=Inf,
    show.legend = F,
    stat = "sf_coordinates"
  ) + labs(subtitle = "Period 2: 1996 ~ 2000\nViolation Type: Empowerment Rights") +
  theme_void() + theme(legend.title = element_blank())

p2v1 + p2v2 + patchwork::plot_layout(ncol = 2)
#ggsave("p2m.png", width = 20, height = 10, units = "in")

p3v1 <- 
  north_korea |> 
  ggplot() +
  geom_sf(fill = "white") + 
  geom_sf(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P3" & 
                      violation.category %in% "Physical Integrity Rights"),
    aes(geometry = geometry, fill = n_agg),
    alpha = 0.9, show.legend = TRUE, stat = "sf_coordinates") +
  scale_fill_viridis(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8),
    limits = c(1, 8),
    labels = c("Under 10", "10-50", "50-100", "100-200", 
               "200-300", "300-400", "400-500", "Over 500"),
    direction = -1) +
  ggrepel::geom_label_repel(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P3" &
                      violation.category %in% "Physical Integrity Rights"),
    aes(geometry = geometry, label = n),
    max.overlaps=Inf,
    show.legend = F,
    stat = "sf_coordinates"
  ) + labs(subtitle = "Period 3: 2001 ~ 2005\nViolation Type: Physical Integrity Rights") +
  theme_void() + theme(legend.title = element_blank())

p3v2 <-
  north_korea |> 
  ggplot() +
  geom_sf(fill = "white") + 
  geom_sf(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P3" & 
                      violation.category %in% "Empowerment Rights"),
    aes(geometry = geometry, fill = n_agg),
    alpha = 0.9, show.legend = TRUE, stat = "sf_coordinates") +
  scale_fill_viridis(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8),
    limits = c(1, 8),
    labels = c("Under 10", "10-50", "50-100", "100-200", 
               "200-300", "300-400", "400-500", "Over 500"),
    direction = -1) +
  ggrepel::geom_label_repel(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P3" &
                      violation.category %in% "Empowerment Rights"),
    aes(geometry = geometry, label = n),
    max.overlaps=Inf,
    show.legend = F,
    stat = "sf_coordinates"
  ) + labs(subtitle = "Period 3: 2001 ~ 2005\nViolation Type: Empowerment Rights") +
  theme_void() + theme(legend.title = element_blank())

p3v1 + p3v2 + patchwork::plot_layout(ncol = 2)
#ggsave("p3m.png", width = 20, height = 10, units = "in")

p4v1 <- 
  north_korea |> 
  ggplot() +
  geom_sf(fill = "white") + 
  geom_sf(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P4" & 
                      violation.category %in% "Physical Integrity Rights"),
    aes(geometry = geometry, fill = n_agg),
    alpha = 0.9, show.legend = TRUE, stat = "sf_coordinates") +
  scale_fill_viridis(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8),
    limits = c(1, 8),
    labels = c("Under 10", "10-50", "50-100", "100-200", 
               "200-300", "300-400", "400-500", "Over 500"),
    direction = -1) +
  ggrepel::geom_label_repel(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P4" &
                      violation.category %in% "Physical Integrity Rights"),
    aes(geometry = geometry, label = n),
    max.overlaps=Inf,
    show.legend = F,
    stat = "sf_coordinates"
  ) + labs(subtitle = "Period 4: 2006 ~ 2010\nViolation Type: Physical Integrity Rights") +
  theme_void() + theme(legend.title = element_blank())

p4v2 <-
  north_korea |> 
  ggplot() +
  geom_sf(fill = "white") + 
  geom_sf(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P4" & 
                      violation.category %in% "Empowerment Rights"),
    aes(geometry = geometry, fill = n_agg),
    alpha = 0.9, show.legend = TRUE, stat = "sf_coordinates") +
  scale_fill_viridis(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8),
    limits = c(1, 8),
    labels = c("Under 10", "10-50", "50-100", "100-200", 
               "200-300", "300-400", "400-500", "Over 500"),
    direction = -1) +
  ggrepel::geom_label_repel(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P4" &
                      violation.category %in% "Empowerment Rights"),
    aes(geometry = geometry, label = n),
    max.overlaps=Inf,
    show.legend = F,
    stat = "sf_coordinates"
  ) + labs(subtitle = "Period 4: 2006 ~ 2010\nViolation Type: Empowerment Rights") +
  theme_void() + theme(legend.title = element_blank())

p4v1 + p4v2 + patchwork::plot_layout(ncol = 2)
#ggsave("p4m.png", width = 20, height = 10, units = "in")

p5v1 <- 
  north_korea |> 
  ggplot() +
  geom_sf(fill = "white") + 
  geom_sf(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P5" & 
                      violation.category %in% "Physical Integrity Rights"),
    aes(geometry = geometry, fill = n_agg),
    alpha = 0.9, show.legend = TRUE, stat = "sf_coordinates") +
  scale_fill_viridis(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8),
    limits = c(1, 8),
    labels = c("Under 10", "10-50", "50-100", "100-200", 
               "200-300", "300-400", "400-500", "Over 500"),
    direction = -1) +
  ggrepel::geom_label_repel(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P5" &
                      violation.category %in% "Physical Integrity Rights"),
    aes(geometry = geometry, label = n),
    max.overlaps=Inf,
    show.legend = F,
    stat = "sf_coordinates"
  ) + labs(subtitle = "Period 5: 2011 ~ 2015\nViolation Type: Physical Integrity Rights") +
  theme_void() + theme(legend.title = element_blank())

p5v2 <-
  north_korea |> 
  ggplot() +
  geom_sf(fill = "white") + 
  geom_sf(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P5" & 
                      violation.category %in% "Empowerment Rights"),
    aes(geometry = geometry, fill = n_agg),
    alpha = 0.9, show.legend = TRUE, stat = "sf_coordinates") +
  scale_fill_viridis(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8),
    limits = c(1, 8),
    labels = c("Under 10", "10-50", "50-100", "100-200", 
               "200-300", "300-400", "400-500", "Over 500"),
    direction = -1) +
  ggrepel::geom_label_repel(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P5" &
                      violation.category %in% "Empowerment Rights"),
    aes(geometry = geometry, label = n),
    max.overlaps=Inf,
    show.legend = F,
    stat = "sf_coordinates"
  ) + labs(subtitle = "Period 5: 2011 ~ 2015\nViolation Type: Empowerment Rights") +
  theme_void() + theme(legend.title = element_blank())

p5v1 + p5v2 + patchwork::plot_layout(ncol = 2)
#ggsave("p5m.png", width = 20, height = 10, units = "in")

p6v1 <- 
  north_korea |> 
  ggplot() +
  geom_sf(fill = "white") + 
  geom_sf(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P6" & 
                      violation.category %in% "Physical Integrity Rights"),
    aes(geometry = geometry, fill = n_agg),
    alpha = 0.9, show.legend = TRUE, stat = "sf_coordinates") +
  scale_fill_viridis(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8),
    limits = c(1, 8),
    labels = c("Under 10", "10-50", "50-100", "100-200", 
               "200-300", "300-400", "400-500", "Over 500"),
    direction = -1) +
  ggrepel::geom_label_repel(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P6" &
                      violation.category %in% "Physical Integrity Rights"),
    aes(geometry = geometry, label = n),
    max.overlaps=Inf,
    show.legend = F,
    stat = "sf_coordinates"
  ) + labs(subtitle = "Period 6: 2016 ~ 2020\nViolation Type: Physical Integrity Rights") +
  theme_void() + theme(legend.title = element_blank())

p6v2 <-
  north_korea |> 
  ggplot() +
  geom_sf(fill = "white") + 
  geom_sf(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P6" & 
                      violation.category %in% "Empowerment Rights"),
    aes(geometry = geometry, fill = n_agg),
    alpha = 0.9, show.legend = TRUE, stat = "sf_coordinates") +
  scale_fill_viridis(
    breaks = c(1, 2, 3, 4, 5, 6, 7, 8),
    limits = c(1, 8),
    labels = c("Under 10", "10-50", "50-100", "100-200", 
               "200-300", "300-400", "400-500", "Over 500"),
    direction = -1) +
  ggrepel::geom_label_repel(
    data = sum_joined_north_korea |> 
      dplyr::filter(period %in% "P6" &
                      violation.category %in% "Empowerment Rights"),
    aes(geometry = geometry, label = n),
    max.overlaps=Inf,
    show.legend = F,
    stat = "sf_coordinates"
  ) + labs(subtitle = "Period 6: 2016 ~ 2020\nViolation Type: Empowerment Rights") +
  theme_void() + theme(legend.title = element_blank())

p6v1 + p6v2 + patchwork::plot_layout(ncol = 2)
#ggsave("p6m.png", width = 20, height = 10, units = "in")

# p1v1 + p1v2 + p2v1 + p2v2 + p3v1 + p3v2 + p4v1 + p4v2 + p5v1 + p5v2 + p6v1 + p6v2 + patchwork::plot_layout(ncol = 4, nrow = 3)
#ggsave("p.png", width = 48, height = 36, units = "in")
```


```{r, echo=FALSE}

table(data.frame(nk_prisoner$Violation.Type)) %>% .[order(.)]

```
